name: ci-node-workflow
on: [push]
jobs:
 check-application:
  runs-on: ubuntu-latest
  steps:
   - uses: actions/checkout@v2
   - uses: actions/setup-node@v2
     with:
      node-version: '14'
   - run: yarn
   - run: yarn test
   - run: node index.js